//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_Gestion.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CS_Gestion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconApplication32 {
            get {
                object obj = ResourceManager.GetObject("IconApplication32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageCancel32 {
            get {
                object obj = ResourceManager.GetObject("ImageCancel32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageCardonerSistemas {
            get {
                object obj = ResourceManager.GetObject("ImageCardonerSistemas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageClose16 {
            get {
                object obj = ResourceManager.GetObject("ImageClose16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageClose32 {
            get {
                object obj = ResourceManager.GetObject("ImageClose32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageEmail24 {
            get {
                object obj = ResourceManager.GetObject("ImageEmail24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageEmail32 {
            get {
                object obj = ResourceManager.GetObject("ImageEmail32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageEntidad16 {
            get {
                object obj = ResourceManager.GetObject("ImageEntidad16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageEntidad48 {
            get {
                object obj = ResourceManager.GetObject("ImageEntidad48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageExport32 {
            get {
                object obj = ResourceManager.GetObject("ImageExport32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageHombre16 {
            get {
                object obj = ResourceManager.GetObject("ImageHombre16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageHombre48 {
            get {
                object obj = ResourceManager.GetObject("ImageHombre48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageItemAdd32 {
            get {
                object obj = ResourceManager.GetObject("ImageItemAdd32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageItemCopy32 {
            get {
                object obj = ResourceManager.GetObject("ImageItemCopy32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageItemDelete32 {
            get {
                object obj = ResourceManager.GetObject("ImageItemDelete32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageItemEdit32 {
            get {
                object obj = ResourceManager.GetObject("ImageItemEdit32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageLogin48 {
            get {
                object obj = ResourceManager.GetObject("ImageLogin48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageMujer16 {
            get {
                object obj = ResourceManager.GetObject("ImageMujer16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageMujer48 {
            get {
                object obj = ResourceManager.GetObject("ImageMujer48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageNext24 {
            get {
                object obj = ResourceManager.GetObject("ImageNext24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageOk32 {
            get {
                object obj = ResourceManager.GetObject("ImageOk32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImagePrevious24 {
            get {
                object obj = ResourceManager.GetObject("ImagePrevious24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImagePrint24 {
            get {
                object obj = ResourceManager.GetObject("ImagePrint24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImagePrint32 {
            get {
                object obj = ResourceManager.GetObject("ImagePrint32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImagePrintPreview24 {
            get {
                object obj = ResourceManager.GetObject("ImagePrintPreview24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImagePrintPreview32 {
            get {
                object obj = ResourceManager.GetObject("ImagePrintPreview32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageReports32 {
            get {
                object obj = ResourceManager.GetObject("ImageReports32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageSearch16 {
            get {
                object obj = ResourceManager.GetObject("ImageSearch16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageSplash {
            get {
                object obj = ResourceManager.GetObject("ImageSplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageTablas32 {
            get {
                object obj = ResourceManager.GetObject("ImageTablas32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageUsuarioGrupo16 {
            get {
                object obj = ResourceManager.GetObject("ImageUsuarioGrupo16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageUsuarioGrupo161 {
            get {
                object obj = ResourceManager.GetObject("ImageUsuarioGrupo161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageUsuarioGrupo48 {
            get {
                object obj = ResourceManager.GetObject("ImageUsuarioGrupo48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageUsuarioGrupo481 {
            get {
                object obj = ResourceManager.GetObject("ImageUsuarioGrupo481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageWindowCloseAll {
            get {
                object obj = ResourceManager.GetObject("ImageWindowCloseAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageWindowFitToSize {
            get {
                object obj = ResourceManager.GetObject("ImageWindowFitToSize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageWindowTileHorizontally {
            get {
                object obj = ResourceManager.GetObject("ImageWindowTileHorizontally", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageWindowTileVertically {
            get {
                object obj = ResourceManager.GetObject("ImageWindowTileVertically", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al guardar los cambios en la Base de Datos..
        /// </summary>
        internal static string STRING_ERROR_SAVING_CHANGES {
            get {
                return ResourceManager.GetString("STRING_ERROR_SAVING_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femenino.
        /// </summary>
        internal static string STRING_GENERO_FEMENINO {
            get {
                return ResourceManager.GetString("STRING_GENERO_FEMENINO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        internal static string STRING_GENERO_MASCULINO {
            get {
                return ResourceManager.GetString("STRING_GENERO_MASCULINO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Todas».
        /// </summary>
        internal static string STRING_ITEM_ALL_FEMALE {
            get {
                return ResourceManager.GetString("STRING_ITEM_ALL_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Todos».
        /// </summary>
        internal static string STRING_ITEM_ALL_MALE {
            get {
                return ResourceManager.GetString("STRING_ITEM_ALL_MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Completa».
        /// </summary>
        internal static string STRING_ITEM_COMPLETE_FEMALE {
            get {
                return ResourceManager.GetString("STRING_ITEM_COMPLETE_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Completo».
        /// </summary>
        internal static string STRING_ITEM_COMPLETE_MALE {
            get {
                return ResourceManager.GetString("STRING_ITEM_COMPLETE_MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Vacía».
        /// </summary>
        internal static string STRING_ITEM_EMPTY_FEMALE {
            get {
                return ResourceManager.GetString("STRING_ITEM_EMPTY_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Vacío».
        /// </summary>
        internal static string STRING_ITEM_EMPTY_MALE {
            get {
                return ResourceManager.GetString("STRING_ITEM_EMPTY_MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ».
        /// </summary>
        internal static string STRING_ITEM_END_CHAR {
            get {
                return ResourceManager.GetString("STRING_ITEM_END_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Nuevo».
        /// </summary>
        internal static string STRING_ITEM_NEW_MALE {
            get {
                return ResourceManager.GetString("STRING_ITEM_NEW_MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------.
        /// </summary>
        internal static string STRING_ITEM_NONE_CHARS10 {
            get {
                return ResourceManager.GetString("STRING_ITEM_NONE_CHARS10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --.
        /// </summary>
        internal static string STRING_ITEM_NONE_CHARS2 {
            get {
                return ResourceManager.GetString("STRING_ITEM_NONE_CHARS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------------.
        /// </summary>
        internal static string STRING_ITEM_NONE_CHARS20 {
            get {
                return ResourceManager.GetString("STRING_ITEM_NONE_CHARS20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----.
        /// </summary>
        internal static string STRING_ITEM_NONE_CHARS5 {
            get {
                return ResourceManager.GetString("STRING_ITEM_NONE_CHARS5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Ninguno».
        /// </summary>
        internal static string STRING_ITEM_NONE_FEMALE {
            get {
                return ResourceManager.GetString("STRING_ITEM_NONE_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Ninguna».
        /// </summary>
        internal static string STRING_ITEM_NONE_MALE {
            get {
                return ResourceManager.GetString("STRING_ITEM_NONE_MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «No especifica».
        /// </summary>
        internal static string STRING_ITEM_NOT_SPECIFIED {
            get {
                return ResourceManager.GetString("STRING_ITEM_NOT_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «.
        /// </summary>
        internal static string STRING_ITEM_START_CHAR {
            get {
                return ResourceManager.GetString("STRING_ITEM_START_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string STRING_NO {
            get {
                return ResourceManager.GetString("STRING_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra.
        /// </summary>
        internal static string STRING_OPERACIONTIPO_COMPRA {
            get {
                return ResourceManager.GetString("STRING_OPERACIONTIPO_COMPRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta.
        /// </summary>
        internal static string STRING_OPERACIONTIPO_VENTA {
            get {
                return ResourceManager.GetString("STRING_OPERACIONTIPO_VENTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        internal static string STRING_YES {
            get {
                return ResourceManager.GetString("STRING_YES", resourceCulture);
            }
        }
    }
}
