//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_Gestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        public int IdEntidad { get; set; }
        public int IdCheque { get; set; }
        public byte IdCuentaBancaria { get; set; }
        public short IdChequeTalonario { get; set; }
        public int Numero { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public decimal Importe { get; set; }
        public string LibradoA { get; set; }
        public bool NoALaOrden { get; set; }
        public string Referencia { get; set; }
        public string Notas { get; set; }
        public bool EsActivo { get; set; }
        public short IdUsuarioCreacion { get; set; }
        public System.DateTime FechaHoraCreacion { get; set; }
        public short IdUsuarioModificacion { get; set; }
        public System.DateTime FechaHoraModificacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
