//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_Gestion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSGestionContext : DbContext
    {
        public CSGestionContext()
            : base("name=CSGestionContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banco> Banco { get; set; }
        public virtual DbSet<BancoSucursal> BancoSucursal { get; set; }
        public virtual DbSet<Cheque> Cheque { get; set; }
        public virtual DbSet<ChequeTalonario> ChequeTalonario { get; set; }
        public virtual DbSet<ChequeTalonarioTipo> ChequeTalonarioTipo { get; set; }
        public virtual DbSet<CuentaBancariaTipo> CuentaBancariaTipo { get; set; }
        public virtual DbSet<DocumentoTipo> DocumentoTipo { get; set; }
        public virtual DbSet<DomicilioTipo> DomicilioTipo { get; set; }
        public virtual DbSet<EmailTipo> EmailTipo { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Entidad> Entidad { get; set; }
        public virtual DbSet<EntidadCuentaBancaria> EntidadCuentaBancaria { get; set; }
        public virtual DbSet<EntidadDomicilio> EntidadDomicilio { get; set; }
        public virtual DbSet<EntidadEmail> EntidadEmail { get; set; }
        public virtual DbSet<EntidadEmpresa> EntidadEmpresa { get; set; }
        public virtual DbSet<EntidadTelefono> EntidadTelefono { get; set; }
        public virtual DbSet<Localidad> Localidad { get; set; }
        public virtual DbSet<Moneda> Moneda { get; set; }
        public virtual DbSet<Movimiento> Movimiento { get; set; }
        public virtual DbSet<MovimientoAplicacion> MovimientoAplicacion { get; set; }
        public virtual DbSet<MovimientoTipo> MovimientoTipo { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<TelefonoTipo> TelefonoTipo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioGrupo> UsuarioGrupo { get; set; }
        public virtual DbSet<UsuarioGrupoPermiso> UsuarioGrupoPermiso { get; set; }
        public virtual DbSet<Parametro> Parametro { get; set; }
    }
}
