//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_Gestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntidadCuentaBancaria
    {
        public int IdEntidad { get; set; }
        public byte IdCuentaBancaria { get; set; }
        public short IdBanco { get; set; }
        public Nullable<byte> IdCuentaBancariaTipo { get; set; }
        public Nullable<short> Sucursal { get; set; }
        public string Numero { get; set; }
        public string Cbu { get; set; }
        public string CbuAlias { get; set; }
        public string Cuit { get; set; }
        public string Titular { get; set; }
        public string Identificacion { get; set; }
        public string Notas { get; set; }
        public bool EsActivo { get; set; }
        public short IdUsuarioCreacion { get; set; }
        public System.DateTime FechaHoraCreacion { get; set; }
        public short IdUsuarioModificacion { get; set; }
        public System.DateTime FechaHoraModificacion { get; set; }
    
        public virtual Entidad Entidad { get; set; }
        public virtual Usuario UsuarioCreacion { get; set; }
        public virtual Usuario UsuarioModificacion { get; set; }
    }
}
