//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_Gestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntidadEmpresa
    {
        public int IdEntidad { get; set; }
        public byte IdEmpresa { get; set; }
        public short IdUsuarioCreacion { get; set; }
        public System.DateTime FechaHoraCreacion { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Entidad Entidad { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
