//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_Gestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoAplicacion
    {
        public int IdMovimiento { get; set; }
        public int IdMovimientoAplicado { get; set; }
        public decimal ImporteAplicado { get; set; }
        public byte IdEmpresa { get; set; }
    
        public virtual Movimiento MovimientoAplicado { get; set; }
        public virtual Movimiento MovimientoAplicante { get; set; }
    }
}
