//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_Gestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movimiento()
        {
            this.MovimientoAplicacion = new HashSet<MovimientoAplicacion>();
            this.MovimientoAplicacion1 = new HashSet<MovimientoAplicacion>();
        }
    
        public byte IdEmpresa { get; set; }
        public int IdMovimiento { get; set; }
        public byte IdMovimientoTipo { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> IdEntidad { get; set; }
        public string Descripcion { get; set; }
        public decimal ImporteNeto { get; set; }
        public decimal ImporteImpuesto { get; set; }
        public decimal ImporteTotal { get; set; }
        public short IdUsuarioCreacion { get; set; }
        public System.DateTime FechaHoraCreacion { get; set; }
        public short IdUsuarioModificacion { get; set; }
        public System.DateTime FechaHoraModificacion { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual MovimientoTipo MovimientoTipo { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoAplicacion> MovimientoAplicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoAplicacion> MovimientoAplicacion1 { get; set; }
        public virtual Movimiento Movimiento1 { get; set; }
        public virtual Movimiento Movimiento2 { get; set; }
    }
}
