//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_Gestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public string IdParametro { get; set; }
        public string Texto { get; set; }
        public Nullable<int> NumeroEntero { get; set; }
        public Nullable<decimal> NumeroDecimal { get; set; }
        public Nullable<decimal> Moneda { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<bool> SiNo { get; set; }
        public string Notas { get; set; }
    }
}
