//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_Gestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioGrupoPermiso
    {
        public byte IdUsuarioGrupo { get; set; }
        public string IdPermiso { get; set; }
    
        public virtual UsuarioGrupo UsuarioGrupo { get; set; }
    }
}
