//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_Gestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.BancosCreados = new HashSet<Banco>();
            this.BancosModificados = new HashSet<Banco>();
            this.BancoSucursalesCreadas = new HashSet<BancoSucursal>();
            this.BancoSucursalesModificadas = new HashSet<BancoSucursal>();
            this.ChequesCreados = new HashSet<Cheque>();
            this.ChequesModificados = new HashSet<Cheque>();
            this.ChequeTalonariosCreados = new HashSet<ChequeTalonario>();
            this.ChequeTalonariosModificados = new HashSet<ChequeTalonario>();
            this.ChequeTalonarioTipoCreados = new HashSet<ChequeTalonarioTipo>();
            this.ChequeTalonarioTiposModificados = new HashSet<ChequeTalonarioTipo>();
            this.CuentaBancariaTiposCreados = new HashSet<CuentaBancariaTipo>();
            this.CuentaBancariaTiposModificados = new HashSet<CuentaBancariaTipo>();
            this.DocumentoTiposCreados = new HashSet<DocumentoTipo>();
            this.DocumentoTiposModificados = new HashSet<DocumentoTipo>();
            this.DomicilioTiposCreados = new HashSet<DomicilioTipo>();
            this.DomicilioTiposModificados = new HashSet<DomicilioTipo>();
            this.EmailTiposCreados = new HashSet<EmailTipo>();
            this.EmailTiposModificados = new HashSet<EmailTipo>();
            this.Empresa = new HashSet<Empresa>();
            this.EmpresasModificadas = new HashSet<Empresa>();
            this.EntidadesCreadas = new HashSet<Entidad>();
            this.EntidadesModificadas = new HashSet<Entidad>();
            this.EntidadCuentasBancariasCreadas = new HashSet<EntidadCuentaBancaria>();
            this.EntidadCuentasBancariasModificadas = new HashSet<EntidadCuentaBancaria>();
            this.EntidadDomiciliosCreados = new HashSet<EntidadDomicilio>();
            this.EntidadDomiciliosModificados = new HashSet<EntidadDomicilio>();
            this.EntidadEmailsCreados = new HashSet<EntidadEmail>();
            this.EntidadEmailsModificados = new HashSet<EntidadEmail>();
            this.EntidadEmpresa = new HashSet<EntidadEmpresa>();
            this.EntidadTelefonosCreados = new HashSet<EntidadTelefono>();
            this.EntidadTelefonosModificados = new HashSet<EntidadTelefono>();
            this.MonedasCreadas = new HashSet<Moneda>();
            this.MonedasModificadas = new HashSet<Moneda>();
            this.MovimientosCreados = new HashSet<Movimiento>();
            this.MovimientosModificados = new HashSet<Movimiento>();
            this.MovimientoTiposCreados = new HashSet<MovimientoTipo>();
            this.MovimientoTiposModificados = new HashSet<MovimientoTipo>();
            this.TelefonoTiposCreados = new HashSet<TelefonoTipo>();
            this.TelefonoTiposModificados = new HashSet<TelefonoTipo>();
            this.UsuariosCreados = new HashSet<Usuario>();
            this.UsuariosModificados = new HashSet<Usuario>();
            this.UsuarioGruposCreados = new HashSet<UsuarioGrupo>();
            this.UsuarioGruposModificados = new HashSet<UsuarioGrupo>();
            this.EntidadCategoriasCreadas = new HashSet<EntidadCategoria>();
            this.EntidadCategoriasModificadas = new HashSet<EntidadCategoria>();
            this.EntidadEntidadCategoria = new HashSet<EntidadEntidadCategoria>();
        }
    
        public short IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Password { get; set; }
        public string Genero { get; set; }
        public byte IdUsuarioGrupo { get; set; }
        public string Notas { get; set; }
        public bool EsActivo { get; set; }
        public short IdUsuarioCreacion { get; set; }
        public System.DateTime FechaHoraCreacion { get; set; }
        public short IdUsuarioModificacion { get; set; }
        public System.DateTime FechaHoraModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Banco> BancosCreados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Banco> BancosModificados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BancoSucursal> BancoSucursalesCreadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BancoSucursal> BancoSucursalesModificadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cheque> ChequesCreados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cheque> ChequesModificados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChequeTalonario> ChequeTalonariosCreados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChequeTalonario> ChequeTalonariosModificados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChequeTalonarioTipo> ChequeTalonarioTipoCreados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChequeTalonarioTipo> ChequeTalonarioTiposModificados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaBancariaTipo> CuentaBancariaTiposCreados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaBancariaTipo> CuentaBancariaTiposModificados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoTipo> DocumentoTiposCreados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoTipo> DocumentoTiposModificados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DomicilioTipo> DomicilioTiposCreados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DomicilioTipo> DomicilioTiposModificados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailTipo> EmailTiposCreados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailTipo> EmailTiposModificados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empresa> Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empresa> EmpresasModificadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entidad> EntidadesCreadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entidad> EntidadesModificadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadCuentaBancaria> EntidadCuentasBancariasCreadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadCuentaBancaria> EntidadCuentasBancariasModificadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadDomicilio> EntidadDomiciliosCreados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadDomicilio> EntidadDomiciliosModificados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadEmail> EntidadEmailsCreados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadEmail> EntidadEmailsModificados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadEmpresa> EntidadEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadTelefono> EntidadTelefonosCreados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadTelefono> EntidadTelefonosModificados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Moneda> MonedasCreadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Moneda> MonedasModificadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento> MovimientosCreados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento> MovimientosModificados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoTipo> MovimientoTiposCreados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoTipo> MovimientoTiposModificados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TelefonoTipo> TelefonoTiposCreados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TelefonoTipo> TelefonoTiposModificados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> UsuariosCreados { get; set; }
        public virtual Usuario UsuarioCreacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> UsuariosModificados { get; set; }
        public virtual Usuario UsuarioModificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioGrupo> UsuarioGruposCreados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioGrupo> UsuarioGruposModificados { get; set; }
        public virtual UsuarioGrupo UsuarioGrupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadCategoria> EntidadCategoriasCreadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadCategoria> EntidadCategoriasModificadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadEntidadCategoria> EntidadEntidadCategoria { get; set; }
    }
}
